// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p_test.proto

package com.wjybxx.fastjgame.protobuffer;

public final class p_test {
  private p_test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code fastjgame.ERole}
   */
  public enum ERole
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NAME = 0;</code>
     */
    NAME(0),
    /**
     * <code>AGE = 1;</code>
     */
    AGE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NAME = 0;</code>
     */
    public static final int NAME_VALUE = 0;
    /**
     * <code>AGE = 1;</code>
     */
    public static final int AGE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ERole valueOf(int value) {
      return forNumber(value);
    }

    public static ERole forNumber(int value) {
      switch (value) {
        case 0: return NAME;
        case 1: return AGE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ERole>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ERole> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ERole>() {
            public ERole findValueByNumber(int number) {
              return ERole.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.wjybxx.fastjgame.protobuffer.p_test.getDescriptor().getEnumTypes().get(0);
    }

    private static final ERole[] VALUES = values();

    public static ERole valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ERole(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:fastjgame.ERole)
  }

  public interface p_helloworldOrBuilder extends
      // @@protoc_insertion_point(interface_extends:fastjgame.p_helloworld)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 a = 1;</code>
     */
    int getA();

    /**
     * <code>int64 b = 2;</code>
     */
    long getB();

    /**
     * <code>repeated int32 c = 3;</code>
     */
    java.util.List<java.lang.Integer> getCList();
    /**
     * <code>repeated int32 c = 3;</code>
     */
    int getCCount();
    /**
     * <code>repeated int32 c = 3;</code>
     */
    int getC(int index);

    /**
     * <code>map&lt;int32, int64&gt; d = 4;</code>
     */
    int getDCount();
    /**
     * <code>map&lt;int32, int64&gt; d = 4;</code>
     */
    boolean containsD(
        int key);
    /**
     * Use {@link #getDMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, java.lang.Long>
    getD();
    /**
     * <code>map&lt;int32, int64&gt; d = 4;</code>
     */
    java.util.Map<java.lang.Integer, java.lang.Long>
    getDMap();
    /**
     * <code>map&lt;int32, int64&gt; d = 4;</code>
     */

    long getDOrDefault(
        int key,
        long defaultValue);
    /**
     * <code>map&lt;int32, int64&gt; d = 4;</code>
     */

    long getDOrThrow(
        int key);

    /**
     * <code>string e = 5;</code>
     */
    java.lang.String getE();
    /**
     * <code>string e = 5;</code>
     */
    com.google.protobuf.ByteString
        getEBytes();

    /**
     * <code>bool f = 6;</code>
     */
    boolean getF();

    /**
     * <code>float g = 7;</code>
     */
    float getG();

    /**
     * <code>double h = 8;</code>
     */
    double getH();

    /**
     * <code>bytes i = 9;</code>
     */
    com.google.protobuf.ByteString getI();

    /**
     * <code>.fastjgame.p_ss j = 10;</code>
     */
    boolean hasJ();
    /**
     * <code>.fastjgame.p_ss j = 10;</code>
     */
    com.wjybxx.fastjgame.protobuffer.p_test.p_ss getJ();
    /**
     * <code>.fastjgame.p_ss j = 10;</code>
     */
    com.wjybxx.fastjgame.protobuffer.p_test.p_ssOrBuilder getJOrBuilder();

    /**
     * <code>.fastjgame.ERole k = 11;</code>
     */
    int getKValue();
    /**
     * <code>.fastjgame.ERole k = 11;</code>
     */
    com.wjybxx.fastjgame.protobuffer.p_test.ERole getK();
  }
  /**
   * <pre>
   * 测试各种情况，在编译时是什么情况
   * </pre>
   *
   * Protobuf type {@code fastjgame.p_helloworld}
   */
  public  static final class p_helloworld extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:fastjgame.p_helloworld)
      p_helloworldOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use p_helloworld.newBuilder() to construct.
    private p_helloworld(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private p_helloworld() {
      c_ = emptyIntList();
      e_ = "";
      i_ = com.google.protobuf.ByteString.EMPTY;
      k_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private p_helloworld(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              a_ = input.readInt32();
              break;
            }
            case 16: {

              b_ = input.readInt64();
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                c_ = newIntList();
                mutable_bitField0_ |= 0x00000004;
              }
              c_.addInt(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) != 0) && input.getBytesUntilLimit() > 0) {
                c_ = newIntList();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                c_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                d_ = com.google.protobuf.MapField.newMapField(
                    DDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000008;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Long>
              d__ = input.readMessage(
                  DDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              d_.getMutableMap().put(
                  d__.getKey(), d__.getValue());
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              e_ = s;
              break;
            }
            case 48: {

              f_ = input.readBool();
              break;
            }
            case 61: {

              g_ = input.readFloat();
              break;
            }
            case 65: {

              h_ = input.readDouble();
              break;
            }
            case 74: {

              i_ = input.readBytes();
              break;
            }
            case 82: {
              com.wjybxx.fastjgame.protobuffer.p_test.p_ss.Builder subBuilder = null;
              if (j_ != null) {
                subBuilder = j_.toBuilder();
              }
              j_ = input.readMessage(com.wjybxx.fastjgame.protobuffer.p_test.p_ss.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(j_);
                j_ = subBuilder.buildPartial();
              }

              break;
            }
            case 88: {
              int rawValue = input.readEnum();

              k_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          c_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wjybxx.fastjgame.protobuffer.p_test.internal_static_fastjgame_p_helloworld_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetD();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wjybxx.fastjgame.protobuffer.p_test.internal_static_fastjgame_p_helloworld_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld.class, com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld.Builder.class);
    }

    private int bitField0_;
    public static final int A_FIELD_NUMBER = 1;
    private int a_;
    /**
     * <code>int32 a = 1;</code>
     */
    public int getA() {
      return a_;
    }

    public static final int B_FIELD_NUMBER = 2;
    private long b_;
    /**
     * <code>int64 b = 2;</code>
     */
    public long getB() {
      return b_;
    }

    public static final int C_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.IntList c_;
    /**
     * <code>repeated int32 c = 3;</code>
     */
    public java.util.List<java.lang.Integer>
        getCList() {
      return c_;
    }
    /**
     * <code>repeated int32 c = 3;</code>
     */
    public int getCCount() {
      return c_.size();
    }
    /**
     * <code>repeated int32 c = 3;</code>
     */
    public int getC(int index) {
      return c_.getInt(index);
    }
    private int cMemoizedSerializedSize = -1;

    public static final int D_FIELD_NUMBER = 4;
    private static final class DDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, java.lang.Long> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, java.lang.Long>newDefaultInstance(
                  com.wjybxx.fastjgame.protobuffer.p_test.internal_static_fastjgame_p_helloworld_DEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.INT64,
                  0L);
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.Long> d_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Long>
    internalGetD() {
      if (d_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            DDefaultEntryHolder.defaultEntry);
      }
      return d_;
    }

    public int getDCount() {
      return internalGetD().getMap().size();
    }
    /**
     * <code>map&lt;int32, int64&gt; d = 4;</code>
     */

    public boolean containsD(
        int key) {
      
      return internalGetD().getMap().containsKey(key);
    }
    /**
     * Use {@link #getDMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Long> getD() {
      return getDMap();
    }
    /**
     * <code>map&lt;int32, int64&gt; d = 4;</code>
     */

    public java.util.Map<java.lang.Integer, java.lang.Long> getDMap() {
      return internalGetD().getMap();
    }
    /**
     * <code>map&lt;int32, int64&gt; d = 4;</code>
     */

    public long getDOrDefault(
        int key,
        long defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.Long> map =
          internalGetD().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, int64&gt; d = 4;</code>
     */

    public long getDOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.Long> map =
          internalGetD().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int E_FIELD_NUMBER = 5;
    private volatile java.lang.Object e_;
    /**
     * <code>string e = 5;</code>
     */
    public java.lang.String getE() {
      java.lang.Object ref = e_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        e_ = s;
        return s;
      }
    }
    /**
     * <code>string e = 5;</code>
     */
    public com.google.protobuf.ByteString
        getEBytes() {
      java.lang.Object ref = e_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        e_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int F_FIELD_NUMBER = 6;
    private boolean f_;
    /**
     * <code>bool f = 6;</code>
     */
    public boolean getF() {
      return f_;
    }

    public static final int G_FIELD_NUMBER = 7;
    private float g_;
    /**
     * <code>float g = 7;</code>
     */
    public float getG() {
      return g_;
    }

    public static final int H_FIELD_NUMBER = 8;
    private double h_;
    /**
     * <code>double h = 8;</code>
     */
    public double getH() {
      return h_;
    }

    public static final int I_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString i_;
    /**
     * <code>bytes i = 9;</code>
     */
    public com.google.protobuf.ByteString getI() {
      return i_;
    }

    public static final int J_FIELD_NUMBER = 10;
    private com.wjybxx.fastjgame.protobuffer.p_test.p_ss j_;
    /**
     * <code>.fastjgame.p_ss j = 10;</code>
     */
    public boolean hasJ() {
      return j_ != null;
    }
    /**
     * <code>.fastjgame.p_ss j = 10;</code>
     */
    public com.wjybxx.fastjgame.protobuffer.p_test.p_ss getJ() {
      return j_ == null ? com.wjybxx.fastjgame.protobuffer.p_test.p_ss.getDefaultInstance() : j_;
    }
    /**
     * <code>.fastjgame.p_ss j = 10;</code>
     */
    public com.wjybxx.fastjgame.protobuffer.p_test.p_ssOrBuilder getJOrBuilder() {
      return getJ();
    }

    public static final int K_FIELD_NUMBER = 11;
    private int k_;
    /**
     * <code>.fastjgame.ERole k = 11;</code>
     */
    public int getKValue() {
      return k_;
    }
    /**
     * <code>.fastjgame.ERole k = 11;</code>
     */
    public com.wjybxx.fastjgame.protobuffer.p_test.ERole getK() {
      @SuppressWarnings("deprecation")
      com.wjybxx.fastjgame.protobuffer.p_test.ERole result = com.wjybxx.fastjgame.protobuffer.p_test.ERole.valueOf(k_);
      return result == null ? com.wjybxx.fastjgame.protobuffer.p_test.ERole.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (a_ != 0) {
        output.writeInt32(1, a_);
      }
      if (b_ != 0L) {
        output.writeInt64(2, b_);
      }
      if (getCList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(cMemoizedSerializedSize);
      }
      for (int i = 0; i < c_.size(); i++) {
        output.writeInt32NoTag(c_.getInt(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetD(),
          DDefaultEntryHolder.defaultEntry,
          4);
      if (!getEBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, e_);
      }
      if (f_ != false) {
        output.writeBool(6, f_);
      }
      if (g_ != 0F) {
        output.writeFloat(7, g_);
      }
      if (h_ != 0D) {
        output.writeDouble(8, h_);
      }
      if (!i_.isEmpty()) {
        output.writeBytes(9, i_);
      }
      if (j_ != null) {
        output.writeMessage(10, getJ());
      }
      if (k_ != com.wjybxx.fastjgame.protobuffer.p_test.ERole.NAME.getNumber()) {
        output.writeEnum(11, k_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (a_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, a_);
      }
      if (b_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, b_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < c_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(c_.getInt(i));
        }
        size += dataSize;
        if (!getCList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        cMemoizedSerializedSize = dataSize;
      }
      for (java.util.Map.Entry<java.lang.Integer, java.lang.Long> entry
           : internalGetD().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Long>
        d__ = DDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, d__);
      }
      if (!getEBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, e_);
      }
      if (f_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, f_);
      }
      if (g_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, g_);
      }
      if (h_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, h_);
      }
      if (!i_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, i_);
      }
      if (j_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, getJ());
      }
      if (k_ != com.wjybxx.fastjgame.protobuffer.p_test.ERole.NAME.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(11, k_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld)) {
        return super.equals(obj);
      }
      com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld other = (com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld) obj;

      if (getA()
          != other.getA()) return false;
      if (getB()
          != other.getB()) return false;
      if (!getCList()
          .equals(other.getCList())) return false;
      if (!internalGetD().equals(
          other.internalGetD())) return false;
      if (!getE()
          .equals(other.getE())) return false;
      if (getF()
          != other.getF()) return false;
      if (java.lang.Float.floatToIntBits(getG())
          != java.lang.Float.floatToIntBits(
              other.getG())) return false;
      if (java.lang.Double.doubleToLongBits(getH())
          != java.lang.Double.doubleToLongBits(
              other.getH())) return false;
      if (!getI()
          .equals(other.getI())) return false;
      if (hasJ() != other.hasJ()) return false;
      if (hasJ()) {
        if (!getJ()
            .equals(other.getJ())) return false;
      }
      if (k_ != other.k_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + A_FIELD_NUMBER;
      hash = (53 * hash) + getA();
      hash = (37 * hash) + B_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getB());
      if (getCCount() > 0) {
        hash = (37 * hash) + C_FIELD_NUMBER;
        hash = (53 * hash) + getCList().hashCode();
      }
      if (!internalGetD().getMap().isEmpty()) {
        hash = (37 * hash) + D_FIELD_NUMBER;
        hash = (53 * hash) + internalGetD().hashCode();
      }
      hash = (37 * hash) + E_FIELD_NUMBER;
      hash = (53 * hash) + getE().hashCode();
      hash = (37 * hash) + F_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getF());
      hash = (37 * hash) + G_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getG());
      hash = (37 * hash) + H_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getH()));
      hash = (37 * hash) + I_FIELD_NUMBER;
      hash = (53 * hash) + getI().hashCode();
      if (hasJ()) {
        hash = (37 * hash) + J_FIELD_NUMBER;
        hash = (53 * hash) + getJ().hashCode();
      }
      hash = (37 * hash) + K_FIELD_NUMBER;
      hash = (53 * hash) + k_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 测试各种情况，在编译时是什么情况
     * </pre>
     *
     * Protobuf type {@code fastjgame.p_helloworld}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:fastjgame.p_helloworld)
        com.wjybxx.fastjgame.protobuffer.p_test.p_helloworldOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wjybxx.fastjgame.protobuffer.p_test.internal_static_fastjgame_p_helloworld_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetD();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetMutableD();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wjybxx.fastjgame.protobuffer.p_test.internal_static_fastjgame_p_helloworld_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld.class, com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld.Builder.class);
      }

      // Construct using com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        a_ = 0;

        b_ = 0L;

        c_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000004);
        internalGetMutableD().clear();
        e_ = "";

        f_ = false;

        g_ = 0F;

        h_ = 0D;

        i_ = com.google.protobuf.ByteString.EMPTY;

        if (jBuilder_ == null) {
          j_ = null;
        } else {
          j_ = null;
          jBuilder_ = null;
        }
        k_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wjybxx.fastjgame.protobuffer.p_test.internal_static_fastjgame_p_helloworld_descriptor;
      }

      @java.lang.Override
      public com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld getDefaultInstanceForType() {
        return com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld.getDefaultInstance();
      }

      @java.lang.Override
      public com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld build() {
        com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld buildPartial() {
        com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld result = new com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.a_ = a_;
        result.b_ = b_;
        if (((bitField0_ & 0x00000004) != 0)) {
          c_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.c_ = c_;
        result.d_ = internalGetD();
        result.d_.makeImmutable();
        result.e_ = e_;
        result.f_ = f_;
        result.g_ = g_;
        result.h_ = h_;
        result.i_ = i_;
        if (jBuilder_ == null) {
          result.j_ = j_;
        } else {
          result.j_ = jBuilder_.build();
        }
        result.k_ = k_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld) {
          return mergeFrom((com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld other) {
        if (other == com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld.getDefaultInstance()) return this;
        if (other.getA() != 0) {
          setA(other.getA());
        }
        if (other.getB() != 0L) {
          setB(other.getB());
        }
        if (!other.c_.isEmpty()) {
          if (c_.isEmpty()) {
            c_ = other.c_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureCIsMutable();
            c_.addAll(other.c_);
          }
          onChanged();
        }
        internalGetMutableD().mergeFrom(
            other.internalGetD());
        if (!other.getE().isEmpty()) {
          e_ = other.e_;
          onChanged();
        }
        if (other.getF() != false) {
          setF(other.getF());
        }
        if (other.getG() != 0F) {
          setG(other.getG());
        }
        if (other.getH() != 0D) {
          setH(other.getH());
        }
        if (other.getI() != com.google.protobuf.ByteString.EMPTY) {
          setI(other.getI());
        }
        if (other.hasJ()) {
          mergeJ(other.getJ());
        }
        if (other.k_ != 0) {
          setKValue(other.getKValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int a_ ;
      /**
       * <code>int32 a = 1;</code>
       */
      public int getA() {
        return a_;
      }
      /**
       * <code>int32 a = 1;</code>
       */
      public Builder setA(int value) {
        
        a_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 a = 1;</code>
       */
      public Builder clearA() {
        
        a_ = 0;
        onChanged();
        return this;
      }

      private long b_ ;
      /**
       * <code>int64 b = 2;</code>
       */
      public long getB() {
        return b_;
      }
      /**
       * <code>int64 b = 2;</code>
       */
      public Builder setB(long value) {
        
        b_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 b = 2;</code>
       */
      public Builder clearB() {
        
        b_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList c_ = emptyIntList();
      private void ensureCIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          c_ = mutableCopy(c_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int32 c = 3;</code>
       */
      public java.util.List<java.lang.Integer>
          getCList() {
        return ((bitField0_ & 0x00000004) != 0) ?
                 java.util.Collections.unmodifiableList(c_) : c_;
      }
      /**
       * <code>repeated int32 c = 3;</code>
       */
      public int getCCount() {
        return c_.size();
      }
      /**
       * <code>repeated int32 c = 3;</code>
       */
      public int getC(int index) {
        return c_.getInt(index);
      }
      /**
       * <code>repeated int32 c = 3;</code>
       */
      public Builder setC(
          int index, int value) {
        ensureCIsMutable();
        c_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 c = 3;</code>
       */
      public Builder addC(int value) {
        ensureCIsMutable();
        c_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 c = 3;</code>
       */
      public Builder addAllC(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureCIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, c_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 c = 3;</code>
       */
      public Builder clearC() {
        c_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, java.lang.Long> d_;
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Long>
      internalGetD() {
        if (d_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              DDefaultEntryHolder.defaultEntry);
        }
        return d_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Long>
      internalGetMutableD() {
        onChanged();;
        if (d_ == null) {
          d_ = com.google.protobuf.MapField.newMapField(
              DDefaultEntryHolder.defaultEntry);
        }
        if (!d_.isMutable()) {
          d_ = d_.copy();
        }
        return d_;
      }

      public int getDCount() {
        return internalGetD().getMap().size();
      }
      /**
       * <code>map&lt;int32, int64&gt; d = 4;</code>
       */

      public boolean containsD(
          int key) {
        
        return internalGetD().getMap().containsKey(key);
      }
      /**
       * Use {@link #getDMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.Long> getD() {
        return getDMap();
      }
      /**
       * <code>map&lt;int32, int64&gt; d = 4;</code>
       */

      public java.util.Map<java.lang.Integer, java.lang.Long> getDMap() {
        return internalGetD().getMap();
      }
      /**
       * <code>map&lt;int32, int64&gt; d = 4;</code>
       */

      public long getDOrDefault(
          int key,
          long defaultValue) {
        
        java.util.Map<java.lang.Integer, java.lang.Long> map =
            internalGetD().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int32, int64&gt; d = 4;</code>
       */

      public long getDOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, java.lang.Long> map =
            internalGetD().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearD() {
        internalGetMutableD().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;int32, int64&gt; d = 4;</code>
       */

      public Builder removeD(
          int key) {
        
        internalGetMutableD().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.Long>
      getMutableD() {
        return internalGetMutableD().getMutableMap();
      }
      /**
       * <code>map&lt;int32, int64&gt; d = 4;</code>
       */
      public Builder putD(
          int key,
          long value) {
        
        
        internalGetMutableD().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;int32, int64&gt; d = 4;</code>
       */

      public Builder putAllD(
          java.util.Map<java.lang.Integer, java.lang.Long> values) {
        internalGetMutableD().getMutableMap()
            .putAll(values);
        return this;
      }

      private java.lang.Object e_ = "";
      /**
       * <code>string e = 5;</code>
       */
      public java.lang.String getE() {
        java.lang.Object ref = e_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          e_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string e = 5;</code>
       */
      public com.google.protobuf.ByteString
          getEBytes() {
        java.lang.Object ref = e_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          e_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string e = 5;</code>
       */
      public Builder setE(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        e_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string e = 5;</code>
       */
      public Builder clearE() {
        
        e_ = getDefaultInstance().getE();
        onChanged();
        return this;
      }
      /**
       * <code>string e = 5;</code>
       */
      public Builder setEBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        e_ = value;
        onChanged();
        return this;
      }

      private boolean f_ ;
      /**
       * <code>bool f = 6;</code>
       */
      public boolean getF() {
        return f_;
      }
      /**
       * <code>bool f = 6;</code>
       */
      public Builder setF(boolean value) {
        
        f_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool f = 6;</code>
       */
      public Builder clearF() {
        
        f_ = false;
        onChanged();
        return this;
      }

      private float g_ ;
      /**
       * <code>float g = 7;</code>
       */
      public float getG() {
        return g_;
      }
      /**
       * <code>float g = 7;</code>
       */
      public Builder setG(float value) {
        
        g_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float g = 7;</code>
       */
      public Builder clearG() {
        
        g_ = 0F;
        onChanged();
        return this;
      }

      private double h_ ;
      /**
       * <code>double h = 8;</code>
       */
      public double getH() {
        return h_;
      }
      /**
       * <code>double h = 8;</code>
       */
      public Builder setH(double value) {
        
        h_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double h = 8;</code>
       */
      public Builder clearH() {
        
        h_ = 0D;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString i_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes i = 9;</code>
       */
      public com.google.protobuf.ByteString getI() {
        return i_;
      }
      /**
       * <code>bytes i = 9;</code>
       */
      public Builder setI(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        i_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes i = 9;</code>
       */
      public Builder clearI() {
        
        i_ = getDefaultInstance().getI();
        onChanged();
        return this;
      }

      private com.wjybxx.fastjgame.protobuffer.p_test.p_ss j_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.wjybxx.fastjgame.protobuffer.p_test.p_ss, com.wjybxx.fastjgame.protobuffer.p_test.p_ss.Builder, com.wjybxx.fastjgame.protobuffer.p_test.p_ssOrBuilder> jBuilder_;
      /**
       * <code>.fastjgame.p_ss j = 10;</code>
       */
      public boolean hasJ() {
        return jBuilder_ != null || j_ != null;
      }
      /**
       * <code>.fastjgame.p_ss j = 10;</code>
       */
      public com.wjybxx.fastjgame.protobuffer.p_test.p_ss getJ() {
        if (jBuilder_ == null) {
          return j_ == null ? com.wjybxx.fastjgame.protobuffer.p_test.p_ss.getDefaultInstance() : j_;
        } else {
          return jBuilder_.getMessage();
        }
      }
      /**
       * <code>.fastjgame.p_ss j = 10;</code>
       */
      public Builder setJ(com.wjybxx.fastjgame.protobuffer.p_test.p_ss value) {
        if (jBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          j_ = value;
          onChanged();
        } else {
          jBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.fastjgame.p_ss j = 10;</code>
       */
      public Builder setJ(
          com.wjybxx.fastjgame.protobuffer.p_test.p_ss.Builder builderForValue) {
        if (jBuilder_ == null) {
          j_ = builderForValue.build();
          onChanged();
        } else {
          jBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.fastjgame.p_ss j = 10;</code>
       */
      public Builder mergeJ(com.wjybxx.fastjgame.protobuffer.p_test.p_ss value) {
        if (jBuilder_ == null) {
          if (j_ != null) {
            j_ =
              com.wjybxx.fastjgame.protobuffer.p_test.p_ss.newBuilder(j_).mergeFrom(value).buildPartial();
          } else {
            j_ = value;
          }
          onChanged();
        } else {
          jBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.fastjgame.p_ss j = 10;</code>
       */
      public Builder clearJ() {
        if (jBuilder_ == null) {
          j_ = null;
          onChanged();
        } else {
          j_ = null;
          jBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.fastjgame.p_ss j = 10;</code>
       */
      public com.wjybxx.fastjgame.protobuffer.p_test.p_ss.Builder getJBuilder() {
        
        onChanged();
        return getJFieldBuilder().getBuilder();
      }
      /**
       * <code>.fastjgame.p_ss j = 10;</code>
       */
      public com.wjybxx.fastjgame.protobuffer.p_test.p_ssOrBuilder getJOrBuilder() {
        if (jBuilder_ != null) {
          return jBuilder_.getMessageOrBuilder();
        } else {
          return j_ == null ?
              com.wjybxx.fastjgame.protobuffer.p_test.p_ss.getDefaultInstance() : j_;
        }
      }
      /**
       * <code>.fastjgame.p_ss j = 10;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.wjybxx.fastjgame.protobuffer.p_test.p_ss, com.wjybxx.fastjgame.protobuffer.p_test.p_ss.Builder, com.wjybxx.fastjgame.protobuffer.p_test.p_ssOrBuilder> 
          getJFieldBuilder() {
        if (jBuilder_ == null) {
          jBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.wjybxx.fastjgame.protobuffer.p_test.p_ss, com.wjybxx.fastjgame.protobuffer.p_test.p_ss.Builder, com.wjybxx.fastjgame.protobuffer.p_test.p_ssOrBuilder>(
                  getJ(),
                  getParentForChildren(),
                  isClean());
          j_ = null;
        }
        return jBuilder_;
      }

      private int k_ = 0;
      /**
       * <code>.fastjgame.ERole k = 11;</code>
       */
      public int getKValue() {
        return k_;
      }
      /**
       * <code>.fastjgame.ERole k = 11;</code>
       */
      public Builder setKValue(int value) {
        k_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.fastjgame.ERole k = 11;</code>
       */
      public com.wjybxx.fastjgame.protobuffer.p_test.ERole getK() {
        @SuppressWarnings("deprecation")
        com.wjybxx.fastjgame.protobuffer.p_test.ERole result = com.wjybxx.fastjgame.protobuffer.p_test.ERole.valueOf(k_);
        return result == null ? com.wjybxx.fastjgame.protobuffer.p_test.ERole.UNRECOGNIZED : result;
      }
      /**
       * <code>.fastjgame.ERole k = 11;</code>
       */
      public Builder setK(com.wjybxx.fastjgame.protobuffer.p_test.ERole value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        k_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.fastjgame.ERole k = 11;</code>
       */
      public Builder clearK() {
        
        k_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:fastjgame.p_helloworld)
    }

    // @@protoc_insertion_point(class_scope:fastjgame.p_helloworld)
    private static final com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld();
    }

    public static com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<p_helloworld>
        PARSER = new com.google.protobuf.AbstractParser<p_helloworld>() {
      @java.lang.Override
      public p_helloworld parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new p_helloworld(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<p_helloworld> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<p_helloworld> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.wjybxx.fastjgame.protobuffer.p_test.p_helloworld getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface p_ssOrBuilder extends
      // @@protoc_insertion_point(interface_extends:fastjgame.p_ss)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 sa = 1;</code>
     */
    int getSa();

    /**
     * <code>int64 sb = 2;</code>
     */
    long getSb();
  }
  /**
   * Protobuf type {@code fastjgame.p_ss}
   */
  public  static final class p_ss extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:fastjgame.p_ss)
      p_ssOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use p_ss.newBuilder() to construct.
    private p_ss(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private p_ss() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private p_ss(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              sa_ = input.readInt32();
              break;
            }
            case 16: {

              sb_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wjybxx.fastjgame.protobuffer.p_test.internal_static_fastjgame_p_ss_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wjybxx.fastjgame.protobuffer.p_test.internal_static_fastjgame_p_ss_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wjybxx.fastjgame.protobuffer.p_test.p_ss.class, com.wjybxx.fastjgame.protobuffer.p_test.p_ss.Builder.class);
    }

    public static final int SA_FIELD_NUMBER = 1;
    private int sa_;
    /**
     * <code>int32 sa = 1;</code>
     */
    public int getSa() {
      return sa_;
    }

    public static final int SB_FIELD_NUMBER = 2;
    private long sb_;
    /**
     * <code>int64 sb = 2;</code>
     */
    public long getSb() {
      return sb_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sa_ != 0) {
        output.writeInt32(1, sa_);
      }
      if (sb_ != 0L) {
        output.writeInt64(2, sb_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sa_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sa_);
      }
      if (sb_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, sb_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wjybxx.fastjgame.protobuffer.p_test.p_ss)) {
        return super.equals(obj);
      }
      com.wjybxx.fastjgame.protobuffer.p_test.p_ss other = (com.wjybxx.fastjgame.protobuffer.p_test.p_ss) obj;

      if (getSa()
          != other.getSa()) return false;
      if (getSb()
          != other.getSb()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SA_FIELD_NUMBER;
      hash = (53 * hash) + getSa();
      hash = (37 * hash) + SB_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSb());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wjybxx.fastjgame.protobuffer.p_test.p_ss parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_test.p_ss parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_test.p_ss parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_test.p_ss parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_test.p_ss parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_test.p_ss parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_test.p_ss parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_test.p_ss parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_test.p_ss parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_test.p_ss parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_test.p_ss parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_test.p_ss parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wjybxx.fastjgame.protobuffer.p_test.p_ss prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code fastjgame.p_ss}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:fastjgame.p_ss)
        com.wjybxx.fastjgame.protobuffer.p_test.p_ssOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wjybxx.fastjgame.protobuffer.p_test.internal_static_fastjgame_p_ss_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wjybxx.fastjgame.protobuffer.p_test.internal_static_fastjgame_p_ss_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wjybxx.fastjgame.protobuffer.p_test.p_ss.class, com.wjybxx.fastjgame.protobuffer.p_test.p_ss.Builder.class);
      }

      // Construct using com.wjybxx.fastjgame.protobuffer.p_test.p_ss.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sa_ = 0;

        sb_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wjybxx.fastjgame.protobuffer.p_test.internal_static_fastjgame_p_ss_descriptor;
      }

      @java.lang.Override
      public com.wjybxx.fastjgame.protobuffer.p_test.p_ss getDefaultInstanceForType() {
        return com.wjybxx.fastjgame.protobuffer.p_test.p_ss.getDefaultInstance();
      }

      @java.lang.Override
      public com.wjybxx.fastjgame.protobuffer.p_test.p_ss build() {
        com.wjybxx.fastjgame.protobuffer.p_test.p_ss result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.wjybxx.fastjgame.protobuffer.p_test.p_ss buildPartial() {
        com.wjybxx.fastjgame.protobuffer.p_test.p_ss result = new com.wjybxx.fastjgame.protobuffer.p_test.p_ss(this);
        result.sa_ = sa_;
        result.sb_ = sb_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wjybxx.fastjgame.protobuffer.p_test.p_ss) {
          return mergeFrom((com.wjybxx.fastjgame.protobuffer.p_test.p_ss)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wjybxx.fastjgame.protobuffer.p_test.p_ss other) {
        if (other == com.wjybxx.fastjgame.protobuffer.p_test.p_ss.getDefaultInstance()) return this;
        if (other.getSa() != 0) {
          setSa(other.getSa());
        }
        if (other.getSb() != 0L) {
          setSb(other.getSb());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wjybxx.fastjgame.protobuffer.p_test.p_ss parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wjybxx.fastjgame.protobuffer.p_test.p_ss) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int sa_ ;
      /**
       * <code>int32 sa = 1;</code>
       */
      public int getSa() {
        return sa_;
      }
      /**
       * <code>int32 sa = 1;</code>
       */
      public Builder setSa(int value) {
        
        sa_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sa = 1;</code>
       */
      public Builder clearSa() {
        
        sa_ = 0;
        onChanged();
        return this;
      }

      private long sb_ ;
      /**
       * <code>int64 sb = 2;</code>
       */
      public long getSb() {
        return sb_;
      }
      /**
       * <code>int64 sb = 2;</code>
       */
      public Builder setSb(long value) {
        
        sb_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 sb = 2;</code>
       */
      public Builder clearSb() {
        
        sb_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:fastjgame.p_ss)
    }

    // @@protoc_insertion_point(class_scope:fastjgame.p_ss)
    private static final com.wjybxx.fastjgame.protobuffer.p_test.p_ss DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wjybxx.fastjgame.protobuffer.p_test.p_ss();
    }

    public static com.wjybxx.fastjgame.protobuffer.p_test.p_ss getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<p_ss>
        PARSER = new com.google.protobuf.AbstractParser<p_ss>() {
      @java.lang.Override
      public p_ss parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new p_ss(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<p_ss> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<p_ss> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.wjybxx.fastjgame.protobuffer.p_test.p_ss getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fastjgame_p_helloworld_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fastjgame_p_helloworld_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fastjgame_p_helloworld_DEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fastjgame_p_helloworld_DEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fastjgame_p_ss_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fastjgame_p_ss_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014p_test.proto\022\tfastjgame\032\016p_common.prot" +
      "o\"\364\001\n\014p_helloworld\022\t\n\001a\030\001 \001(\005\022\t\n\001b\030\002 \001(\003" +
      "\022\t\n\001c\030\003 \003(\005\022)\n\001d\030\004 \003(\0132\036.fastjgame.p_hel" +
      "loworld.DEntry\022\t\n\001e\030\005 \001(\t\022\t\n\001f\030\006 \001(\010\022\t\n\001" +
      "g\030\007 \001(\002\022\t\n\001h\030\010 \001(\001\022\t\n\001i\030\t \001(\014\022\032\n\001j\030\n \001(\013" +
      "2\017.fastjgame.p_ss\022\033\n\001k\030\013 \001(\0162\020.fastjgame" +
      ".ERole\032(\n\006DEntry\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002" +
      " \001(\003:\0028\001\"\036\n\004p_ss\022\n\n\002sa\030\001 \001(\005\022\n\n\002sb\030\002 \001(\003" +
      "*\032\n\005ERole\022\010\n\004NAME\020\000\022\007\n\003AGE\020\001B,\n com.wjyb" +
      "xx.fastjgame.protobufferB\006p_testH\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.wjybxx.fastjgame.protobuffer.p_common.getDescriptor(),
        }, assigner);
    internal_static_fastjgame_p_helloworld_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_fastjgame_p_helloworld_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fastjgame_p_helloworld_descriptor,
        new java.lang.String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", });
    internal_static_fastjgame_p_helloworld_DEntry_descriptor =
      internal_static_fastjgame_p_helloworld_descriptor.getNestedTypes().get(0);
    internal_static_fastjgame_p_helloworld_DEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fastjgame_p_helloworld_DEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_fastjgame_p_ss_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_fastjgame_p_ss_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fastjgame_p_ss_descriptor,
        new java.lang.String[] { "Sa", "Sb", });
    com.wjybxx.fastjgame.protobuffer.p_common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
